### ISSUE TITLE
Excessive memory consumption

### ISSUE THREAD

**Issue by Banyc** [jjw24/Wox#96] opened 2019-12-10 11:20 UTC
This App takes up as many as 400mb in memory

**Comment by jjw24** [comment] 2019-12-10 12:03
Hey how's it going.

Please provide more information so can better troubleshoot:
1. Do you only have the default Wox plugins installed?
2. Have you installed other plugins, if so please list them.
3. What version of Windows you are using?
4. Are you also getting such high usage with previous Wox versions from this fork?
5. Are you consistently getting 400mb with Wox or just on occasions?
6. I suspect it's the Programs plugin taking up memory, please disable it via settings and let me know if there is a change.

**Comment by theClueless** [comment] 2019-12-17 08:18
@jjw24 I have seen the same problem and done some memory profiling it seems that our images cache is the cause for this.
on my machine, when loading image cache - 250MB, without - 50MB.
and since any new image it finds during query would be added to the cache it will continue to grow throughout the time of Wox running (and during close it would dispose of all the cache expect for 5000 images that he would keep).
I can do some work and tweaking to fix this, I don't see any real reason for that to happen

**Comment by jjw24** [comment] 2020-01-15 10:48
Closing with PR #115. Reopen if still persists.

**Closed as completed by jjw24** 2020-01-15 10:48 UTC
Labels: bug, help wanted
